name: CI
on: [push]
jobs:
  mypy:
    runs-on: ubuntu-latest
    name: Mypy
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        pip install mypy
    - name: mypy
      run: |
        mypy .

  yapf-check:
    name: YAPF Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: run YAPF to test if python code is correctly formatted
      uses: AlexanderMelde/yapf-action@master
      with:
        args: --verbose --diff --style google
