name: CI
on: [push]
jobs:
  mypy:
    runs-on: ubuntu-latest
    name: mypy
    container: le91688/dockerized_mypy:3.8-1.3.0
    steps:
    - name: mypy
      run: |
        .

  yapf:
    runs-on: ubuntu-latest
    container: le91688/dockerized_yapf:3.8-0.33.0
    name: yapf
    steps:
    - uses: actions/checkout@v1
    - name: yapf
      run: |
        --style google --diff farmhand.py

